### ISSUE TITLE
Out of curiosity...

### ISSUE THREAD

**Issue by edwinyzh** [RoPi0n/JB_InternshipTask_FPC#1]
Hello,

Out of curiosity, from the description "JetBrains internship 2019 task.",  JetBrains is a world leading development tools vendor, do they use Pascal internally? Or they are having a plan for FPC ? :)

**Comment by RoPi0n** [comment]
In task I read next phrase: "u can use any languages from tiobe top 50 or any open-source language".
I'm thinking about writing on my own language firstly... Maybe will do that later. But now I have exams and haven't too much time for that and it's will be not funny for auditors I think.

Why all people think bad about object pascal?
That language very powerful and have a lot of features. This is a bad stereotype.
I can write good code on that very quickly. For example - for that task I spend hour and a half of my time while JetBrains give one week for that. And all work well.

I'm know object pascal, c++ and java well. Also learning now kotlin & python.
Developers should select better language for trivially tasks.
Pascal I think best language for easy text parsing and analyse.

Don't worry. On internship we will write all on java & kotlin.
I want to write a part of code of kotlin coroutines debugger :)

**Comment by edwinyzh** [comment]
Hey, I'm not worrying, but instead, I'm a little disappointed to hear that Object Pascal has nothing to do with the JetBrains products - I'm an ObjectPascal fan for a longgggg time!

And I fully agree with you your the Object Pascal language, it's clean and it allows me to develop software quickly and freely. I love it. All my recent projects are based on Delphi (and trying to be prepared for FPC for the future).

**Comment by RoPi0n** [comment]
I see. It's sad but Object Pascal unpopular now. Try to learn C++ or Kotlin.
